# Use Minecraft legacy color codes with '&' (Bukkit will translate them).
# Example: green bold "Home", dark gray chevron, then gray body text.
chatPrefix: "&a&lHome&r &8≫ &7"

# Max number of private homes for non-admins.
maxHomes: 8

# Lines per page for list commands (mine/public/invited).
pageSize: 8
