
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Install Gradle 8.9
        run: |
          set -eux
          curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.9-bin.zip
          unzip -q gradle.zip -d $HOME
          echo "$HOME/gradle-8.9/bin" >> $GITHUB_PATH
          gradle --version

      - name: Build
        run: |
          set -eux
          gradle build --no-daemon --stacktrace

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          draft: false
          prerelease: false
